# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_journo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_pr',
            field=models.BooleanField(default=False),
        ),
    ]
