# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0004_auto_20170105_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_journo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_pr',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PR', 'Public Relations Professional'), ('JOURNO', 'Journalist')], default='PR', max_length=2),
        ),
    ]
