# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0005_auto_20170106_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PR', 'Public Relations Professional'), ('JOURNO', 'Journalist')], max_length=2),
        ),
    ]
