# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0008_conversation_directmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
