# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0009_auto_20170106_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='is_pitch',
        ),
    ]
