# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0010_remove_directmessage_is_pitch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='conversation_id',
            new_name='conversation',
        ),
    ]
