# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0011_auto_20170106_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
