# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0013_auto_20170110_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='pitchy/static/media/'),
        ),
    ]
