# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0015_auto_20170110_1343'),
        ('pitchy', '0011_auto_20170106_1512'),
    ]

    operations = [
    ]
