# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0016_merge_20170111_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='label',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
