# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0017_conversation_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.TextField(),
        ),
    ]
