# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0018_auto_20170113_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='label',
            field=models.SlugField(unique=True),
        ),
    ]
