# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import pitchy.models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchy', '0021_auto_20170121_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(upload_to=pitchy.models.upload_avatar_to),
        ),
    ]
